// Configuration and data constants for the rebuild script

const COLORS = {
  navyBg: "1B2A4A", white: "FFFFFF", altRow: "F2F2F2",
  critRed: "FF0000", highOrange: "FF6600", medYellow: "FFCC00", lowGreen: "00AA00",
  failBg: "FFE0E0", verifyBg: "FFF3CD", passBg: "E8F5E9", stealthBg: "E8E0F0",
  blockedBg: "FFD9B3",
  devFailure: "FF4444", verified: "4CAF50", awaitingQA: "FFC107",
  gradeF: "FF6B6B", gradeC: "FFD93D", gradeB: "6BCB77", gradeA: "4D96FF",
  sectionBg: "2C3E50", sectionBg2: "34495E", sectionBg3: "7F8C8D",
  dangerBg: "E74C3C", warnBg: "F39C12", safeBg: "27AE60", naBg: "BDC3C7",
  lightBlue: "D6EAF8", lightGreen: "D5F5E3", lightRed: "FADBD8", lightYellow: "FEF9E7",
};

const THIN_BORDER = { top:{style:"thin"}, left:{style:"thin"}, bottom:{style:"thin"}, right:{style:"thin"} };

function getExamModeForReg(id) {
  const n = parseInt(id.replace("REG-",""));
  if (n <= 5) return "General";
  if (n <= 14) return "General";
  if (n <= 22) return "Proctored";
  if (n <= 41) return "General";
  if (n <= 52) return "Proctored";
  if (n <= 56) return "General";
  if (n <= 85) return "General";
  if (n <= 105) return "SEB";
  if (n <= 120) return "SEB";
  if (n <= 147) return "SEB Bypass";
  if (n <= 150) return "Admin";
  if (n <= 155) return "Server";
  return "General";
}

function getExamModeForCD(id) {
  const n = parseInt(id.replace("CD-",""));
  if (n <= 12) return "Proctored";
  return "Proctored + SEB";
}

function getExamModeForCS(id) {
  const n = parseInt(id.replace("CS-",""));
  if (n <= 5) return "All Modes";
  if (n <= 13) return "Proctored";
  if (n <= 17) return "Proctored";
  if (n === 18) return "All Modes";
  if (n <= 21) return "All Modes";
  if (n === 22) return "Proctored";
  if (n <= 28) return "Proctored";
  if (n <= 41) return "Proctored + SEB";
  return "SEB Bypass";
}

const SYSTEM_MAP_BLOCKS = {
  title: "EMS EXAM SYSTEM — ARCHITECTURE & SECURITY MAP",
  legend: [
    { text: "PROTECTED", color: COLORS.safeBg },
    { text: "PARTIAL", color: COLORS.warnBg },
    { text: "VULNERABLE", color: COLORS.dangerBg },
    { text: "N/A", color: COLORS.naBg },
  ],
  examModes: [
    { mode: "OFFLINE", desc: "Question paper downloaded.\nExam conducted offline.\nNo software control.", grade: "F", color: COLORS.gradeF },
    { mode: "NON-PROCTORED", desc: "Should have NO restrictions.\nBUG-006: Proctoring still\nenforces even when flag OFF.\nCurrently BLOCKED.", grade: "F", color: COLORS.gradeF },
    { mode: "PROCTORED\n(No SEB)", desc: "Camera + Fullscreen + Screenshot\n+ Malpractice Detection.\n12 detectable cheats caught.\n44 stealth cheats possible.", grade: "C+", color: COLORS.gradeC },
    { mode: "PROCTORED\n+ SEB", desc: "All proctoring + SEB lockdown.\nKiosk mode, keyboard blocks.\nVM detection (bypassable).\n7 bypass vectors exist.", grade: "B", color: COLORS.gradeB },
    { mode: "PROCTORED\n+ SEB + BEK", desc: "All above + Binary Integrity.\nDetects DLL patching.\nBlocks 4 of 7 vectors.\nNOT IMPLEMENTED YET.", grade: "A-", color: COLORS.gradeA },
  ],
  configVars: {
    featureFlags: [
      { flag: "ONLINE_EXAM_PROCTORING", on: "Camera + Fullscreen + Malpractice", off: "Should be no restrictions (BUG-006: STILL ENFORCES!)", bug: "BUG-006" },
      { flag: "PROCTOR_SCREENSHOT", on: "Screenshots captured at interval", off: "No screenshots" },
      { flag: "PROCTOR_WEBCAM", on: "Webcam monitoring + face detection", off: "No webcam" },
    ],
    sebConfig: [
      { setting: ".seb File Upload", desc: "Locks down browser (kiosk, shortcuts blocked)" },
      { setting: "Config Key (64-char hex)", desc: "Validates .seb config integrity — NOT binary integrity!" },
      { setting: "Force Disable SEB", desc: "DANGER: Skip SEB for ALL exams" },
      { setting: "Force Enable SEB", desc: "Force SEB for ALL exams" },
      { setting: "Bypass Validation", desc: "DANGER: Skip config key check (testing only!)" },
      { setting: "Bypass Override", desc: "Global config overrides exam-specific" },
    ],
    serverChecks: [
      { header: "User-Agent (SEB/x.x.x)", validated: "UNKNOWN", risk: "If not checked, old versions accepted" },
      { header: "X-SafeExamBrowser-ConfigKeyHash", validated: "YES", risk: "Only validates .seb config, NOT binaries" },
      { header: "X-SafeExamBrowser-RequestHash (BEK)", validated: "NO — NOT IMPLEMENTED", risk: "#1 vulnerability — ALL DLL attacks succeed" },
    ],
  },
  threatVectors: [
    { id: "V1", name: "Pre-built Patch (SEBPatch)", skill: "None", detectable: "No", blockedBy: "BEK", status: "To Test" },
    { id: "V2", name: "Version Downgrade + Old Patch", skill: "Low", detectable: "Maybe", blockedBy: "Version Check", status: "To Test" },
    { id: "V3", name: "Custom SEB Fork (Open Source)", skill: "Medium", detectable: "No", blockedBy: "BEK", status: "To Test" },
    { id: "V4", name: "AI-Generated Bypass DLLs", skill: "Medium", detectable: "No", blockedBy: "BEK", status: "PoC Ready" },
    { id: "V5", name: "Legacy SEB v2.4 (Zero Security)", skill: "None", detectable: "Maybe", blockedBy: "Version Check", status: "To Test" },
    { id: "V6", name: "VM Anti-Detection (No DLL)", skill: "Medium", detectable: "Partial", blockedBy: "SEB Detection", status: "To Test" },
    { id: "V7", name: "Combination Attack (Full Stealth)", skill: "High", detectable: "No", blockedBy: "Nothing", status: "To Test" },
  ],
};

const SECURITY_MATRIX = [
  { feature: "Fullscreen Lock", offline: "—", nonProc: "—", proctored: "JS-based (bypassable)", seb: "Kernel-level (SEB)", sebBek: "Kernel-level (SEB)" },
  { feature: "Camera / Face Detection", offline: "—", nonProc: "—", proctored: "Yes (if flag ON)", seb: "Yes (if configured)", sebBek: "Yes (if configured)" },
  { feature: "Screenshot Capture", offline: "—", nonProc: "—", proctored: "If PROCTOR_SCREENSHOT ON", seb: "If flag ON", sebBek: "If flag ON" },
  { feature: "Screen Share Required", offline: "—", nonProc: "—", proctored: "Yes (entire screen)", seb: "N/A (SEB controls)", sebBek: "N/A (SEB controls)" },
  { feature: "Block Alt+Tab / Shortcuts", offline: "—", nonProc: "—", proctored: "JS-based (bypassable)", seb: "SEB kernel-level", sebBek: "SEB kernel-level" },
  { feature: "Block Task Manager", offline: "—", nonProc: "—", proctored: "No", seb: "Yes (SEB)", sebBek: "Yes (SEB)" },
  { feature: "Block Clipboard", offline: "—", nonProc: "—", proctored: "JS Ctrl+C/V only", seb: "SEB-level block", sebBek: "SEB-level block" },
  { feature: "Block Print Screen", offline: "—", nonProc: "—", proctored: "No", seb: "Yes (SEB)", sebBek: "Yes (SEB)" },
  { feature: "VM Detection", offline: "—", nonProc: "—", proctored: "No", seb: "Yes (bypassable)", sebBek: "Yes (bypassable)" },
  { feature: "Binary Integrity Check", offline: "—", nonProc: "—", proctored: "N/A", seb: "NO — Config Key only", sebBek: "YES — BEK validates" },
  { feature: "Process Monitoring", offline: "—", nonProc: "—", proctored: "No", seb: "Yes (SEB)", sebBek: "Yes (SEB)" },
  { feature: "URL Filtering", offline: "—", nonProc: "—", proctored: "No", seb: "Yes (SEB)", sebBek: "Yes (SEB)" },
  { feature: "Single Display Enforce", offline: "—", nonProc: "—", proctored: "No", seb: "Yes (SEB)", sebBek: "Yes (SEB)" },
  { feature: "Malpractice Detection", offline: "—", nonProc: "—", proctored: "13 types, weighted", seb: "13 types + SEB blocks", sebBek: "13 types + SEB blocks" },
  { feature: "Session Validation", offline: "—", nonProc: "—", proctored: "Token-based", seb: "Token + SEB headers", sebBek: "Token + SEB + BEK" },
];

const FLAG_COMBOS = [
  { n: 1, proc: "OFF", screen: "OFF", webcam: "OFF", result: "No restrictions (mock exam)", actual: "BUG-006: Still enforces proctoring!", bug: "BUG-006" },
  { n: 2, proc: "OFF", screen: "OFF", webcam: "ON", result: "Webcam only, no fullscreen", actual: "BUG-006: Still enforces proctoring!", bug: "BUG-006" },
  { n: 3, proc: "OFF", screen: "ON", webcam: "OFF", result: "Screenshots only", actual: "BUG-006: Still enforces proctoring!", bug: "BUG-006" },
  { n: 4, proc: "OFF", screen: "ON", webcam: "ON", result: "Screenshots + Webcam only", actual: "BUG-006: Still enforces proctoring!", bug: "BUG-006" },
  { n: 5, proc: "ON", screen: "OFF", webcam: "OFF", result: "Fullscreen + malpractice only", actual: "To Test", bug: "" },
  { n: 6, proc: "ON", screen: "OFF", webcam: "ON", result: "Fullscreen + webcam + malpractice", actual: "To Test", bug: "" },
  { n: 7, proc: "ON", screen: "ON", webcam: "OFF", result: "Fullscreen + screenshots + malpractice", actual: "To Test", bug: "" },
  { n: 8, proc: "ON", screen: "ON", webcam: "ON", result: "Full proctoring (camera + screenshots + malpractice)", actual: "Working baseline", bug: "" },
];

const RISK_REGISTER = [
  { vector: "V1: Pre-built Patch", likelihood: 5, impact: 5, score: 25, level: "CRITICAL" },
  { vector: "V2: Version Downgrade", likelihood: 4, impact: 5, score: 20, level: "CRITICAL" },
  { vector: "V3: Custom Fork", likelihood: 2, impact: 5, score: 10, level: "HIGH" },
  { vector: "V4: AI-Generated DLLs", likelihood: 3, impact: 5, score: 15, level: "CRITICAL" },
  { vector: "V5: Legacy v2.4", likelihood: 3, impact: 5, score: 15, level: "CRITICAL" },
  { vector: "V6: VM Anti-Detection", likelihood: 3, impact: 4, score: 12, level: "HIGH" },
  { vector: "V7: Combination Attack", likelihood: 2, impact: 5, score: 10, level: "HIGH" },
];

module.exports = {
  COLORS, THIN_BORDER, SYSTEM_MAP_BLOCKS, SECURITY_MATRIX, FLAG_COMBOS, RISK_REGISTER,
  getExamModeForReg, getExamModeForCD, getExamModeForCS,
};
