const ExcelJS = require("exceljs");

async function main() {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile("EMS_Exam_Security_TestPlan.xlsx");

  const thinBorder = {
    top: { style: "thin" }, left: { style: "thin" },
    bottom: { style: "thin" }, right: { style: "thin" },
  };
  const COLORS = {
    headerBg: "FF1B2A4A", headerFont: "FFFFFFFF",
    altRow: "FFF2F2F2", white: "FFFFFFFF",
    criticalRed: "FFFF0000", highOrange: "FFFF6600",
    mediumYellow: "FFFFCC00", lowGreen: "FF00AA00",
    statusFail: "FFFFE0E0", statusVerify: "FFFFF3CD",
    statusPass: "FFE8F5E9", statusStealth: "FFE8E0F0",
    statusDetectable: "FFDBEAFE",
  };

  function addRow(ws, data) {
    const row = ws.addRow(data);
    row.font = { size: 10, name: "Calibri" };
    row.alignment = { vertical: "top", wrapText: true };
    const rn = row.number;
    row.fill = { type: "pattern", pattern: "solid", fgColor: { argb: rn % 2 === 0 ? "FFFFFFFF" : "FFF2F2F2" } };
    for (let c = 1; c <= ws.columns.length; c++) row.getCell(c).border = thinBorder;
    return row;
  }

  function applySev(row, colIdx) {
    const v = String(row.getCell(colIdx).value || "").toLowerCase();
    if (v.includes("critical")) {
      row.getCell(colIdx).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.criticalRed } };
      row.getCell(colIdx).font = { bold: true, size: 10, name: "Calibri", color: { argb: COLORS.headerFont } };
    } else if (v.includes("high")) {
      row.getCell(colIdx).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.highOrange } };
      row.getCell(colIdx).font = { bold: true, size: 10, name: "Calibri", color: { argb: COLORS.headerFont } };
    }
  }

  function applyStatus(row, colIdx) {
    const v = String(row.getCell(colIdx).value || "").toLowerCase();
    if (v.includes("fail") || v.includes("blocked")) {
      row.getCell(colIdx).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.statusFail } };
    } else if (v.includes("verify") || v.includes("pending") || v.includes("to test")) {
      row.getCell(colIdx).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.statusVerify } };
    } else if (v.includes("pass") || v.includes("tested")) {
      row.getCell(colIdx).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.statusPass } };
    }
  }

  // =========================================================================
  // SHEET 5: REGRESSION SUITE -- New test cases for all 7 vectors
  // =========================================================================
  const ws5 = wb.getWorksheet("5. Regression Suite");

  const newRegCases = [
    // Vector 4: AI-Generated Bypass DLLs
    ["REG-138", "SEB Bypass - Vector 4", "AI-Generated Bypass DLL - VirtualMachineDetector", "Negative",
      "Student uses AI (ChatGPT/Claude) to analyze open-source SEB code and generate modified VirtualMachineDetector.cs that returns false",
      "SEB source code from GitHub, Visual Studio, .NET Framework SDK",
      "1. Clone SEB repo: git clone https://github.com/SafeExamBrowser/seb-win-refactoring\n2. Open SafeExamBrowser.Monitoring/VirtualMachineDetector.cs\n3. Ask AI: 'Modify IsVirtualMachine() to always return false'\n4. AI generates single-line change in 10 seconds\n5. Build SafeExamBrowser.Monitoring.dll\n6. Copy to C:\\Program Files\\SafeExamBrowser\\Application\\\n7. Launch SEB in VM\n8. Attempt exam",
      "SEB should detect tampering or VM. Without BEK validation, the modified DLL will work because Config Key only validates the .seb config file, not the binaries.",
      "", "Critical", "Medium", "To Test",
      "PoC code created in SEB_Bypass_PoC/ folder. This is the MOST DANGEROUS vector because: (1) always matches current version (no mismatch crash), (2) no download trail, (3) any student with AI access can do it in 15 minutes."],

    ["REG-139", "SEB Bypass - Vector 4", "AI-Generated Bypass DLL - RemoteSessionDetector", "Negative",
      "Student modifies RemoteSessionDetector.cs to bypass remote desktop detection",
      "Same as REG-138",
      "1. Open SafeExamBrowser.Monitoring/RemoteSessionDetector.cs\n2. Modify IsRemoteSession() to return false\n3. Build and replace DLL\n4. Use Remote Desktop to take exam while helper controls the machine",
      "Remote session detection disabled. Helper can take exam remotely.",
      "", "Critical", "Medium", "To Test",
      "RemoteSessionDetector was added in newer SEB versions -- this is why old nxvvvv patches crash (they don't have this class at all)."],

    ["REG-140", "SEB Bypass - Vector 4", "AI-Generated Bypass DLL - IntegrityModule", "Negative",
      "Student modifies IntegrityModule.cs to bypass code signature verification and native VM detection",
      "Same as REG-138",
      "1. Open SafeExamBrowser.Integrity/IntegrityModule.cs\n2. Modify IsVirtualMachine() to return false\n3. Modify TryVerifyCodeSignature() to set isValid=true and return true\n4. Modify TryVerifySessionIntegrity() to set isValid=true\n5. Build SafeExamBrowser.Integrity.dll\n6. Replace in SEB install directory\n7. Launch SEB -- all integrity checks pass",
      "All integrity checks bypassed. SEB reports everything is legitimate.",
      "", "Critical", "Medium", "To Test",
      "IntegrityModule uses native DLL (seb_x64.dll) for BEK calculation which is harder to modify, but the C# wrapper security checks are trivially bypassable."],

    ["REG-141", "SEB Bypass - Vector 4", "AI-Generated Full Bypass (3 DLLs combined)", "Negative",
      "Student replaces all 3 modified DLLs simultaneously for complete bypass",
      "Modified VirtualMachineDetector.cs + RemoteSessionDetector.cs + IntegrityModule.cs compiled",
      "1. Build all 3 modified DLLs from current SEB version source\n2. Copy SafeExamBrowser.Monitoring.dll to SEB install dir\n3. Copy SafeExamBrowser.Integrity.dll to SEB install dir\n4. Launch SEB in VMware with SMBIOS.reflectHost\n5. Take exam normally\n6. Test: Alt+Tab, Task Manager, Ctrl+C, Print Screen\n7. Check if Config Key validation passes\n8. Check server-side logs for any anomaly\n9. Check if BEK header is sent and validated",
      "Complete stealth bypass. SEB runs in VM, all monitoring disabled, Config Key passes. If BEK is not validated server-side, exam completes normally.",
      "", "Critical", "Medium", "To Test",
      "This is the definitive test. If this passes, our application has ZERO defense against AI-generated bypasses without BEK implementation."],

    // Vector 1: SEBPatch (already partially covered, consolidating)
    ["REG-142", "SEB Bypass - Vector 1", "SEBPatch v1.8.1 on SEB v3.10.1 (Latest)", "Negative",
      "Use the actively maintained SEBPatch automated patcher on latest SEB version",
      "SEB v3.10.1.864 installed from SourceForge, SEBPatch v1.8.1 downloaded",
      "1. Uninstall current SEB\n2. Download SEB v3.10.1.864 from sourceforge.net/projects/seb/\n3. Install SEB v3.10.1\n4. Download SEBPatch v1.8.1 from sourceforge.net/projects/sebpatch/\n5. Run patch-seb.exe (8.2 MB automated patcher)\n6. Launch SEB\n7. Test exam access\n8. Test all lockdown features\n9. Run in VM to test VM bypass",
      "If server doesn't enforce SEB version v3.6.0 specifically and doesn't validate BEK: bypass succeeds. Config Key passes because .seb config file is unchanged.",
      "", "Critical", "Low", "To Test",
      "SEBPatch has 194+ weekly downloads. Wiki with instructions. Most likely to be used by students because it requires ZERO technical skill."],

    // Vector 2: Downgrade + Old Patch (consolidating REG-132)
    ["REG-143", "SEB Bypass - Vector 2", "SEB v3.5.0 Downgrade + nxvvvv v3.5.0 Patch", "Negative",
      "Student installs OLD SEB version that matches the old patch",
      "SEB v3.5.0 downloaded from SourceForge (all versions still available)",
      "1. Uninstall current SEB v3.6.0\n2. Download SEB v3.5.0 from sourceforge.net/projects/seb/files/\n3. Install SEB v3.5.0\n4. Apply nxvvvv v3.5.0.544 patch (3 DLL files)\n5. Launch SEB -- should work (no version mismatch)\n6. TRY EXAM: Does server accept SEB v3.5.0?\n7. Check User-Agent header: does it show SEB/3.5.0?\n8. Does our server parse and reject old versions?",
      "If server accepts ANY SEB version: bypass works. If server checks User-Agent for version: this is detectable. CRITICAL TEST: Does our server validate SEB version AT ALL?",
      "", "Critical", "Low", "To Test",
      "This test also reveals whether our server has ANY version enforcement -- a critical gap."],

    // Vector 5: Legacy SEB v2.4
    ["REG-144", "SEB Bypass - Vector 5", "SEB Legacy v2.4 (Zero VM Detection)", "Negative",
      "Student installs SEB v2.4 which has NO VM detection at all",
      "SEB v2.4 from SourceForge",
      "1. Download SEB v2.4.x from sourceforge.net/projects/seb/files/\n2. Install SEB v2.4\n3. Launch in VM\n4. Try exam access\n5. Check if Config Key validation works with v2.4\n6. Check User-Agent: does it show SEB/2.4?\n7. Does our server accept v2.4?",
      "SEB v2.4 has ZERO VM detection, process monitoring, or integrity checks. If server accepts it, student has unrestricted VM access.",
      "", "Critical", "Low", "To Test",
      "v2.4 was pre-refactoring, completely different codebase. No modern security features."],

    // Vector 6: VM Anti-Detection WITHOUT DLL patching
    ["REG-145", "SEB Bypass - Vector 6", "VMware SMBIOS.reflectHost Only (No DLL Patch)", "Negative",
      "Spoof VM manufacturer using SMBIOS reflection with OFFICIAL unmodified SEB",
      "VMware Workstation, official SEB installed",
      "1. Create Windows VM in VMware\n2. Shut down VM\n3. Edit .vmx file: add SMBIOS.reflectHost = \"TRUE\"\n4. Boot VM\n5. Install OFFICIAL SEB (no patches)\n6. Launch SEB\n7. Does SEB detect the VM?\n8. If SEB launches, test exam access",
      "SMBIOS reflection spoofs manufacturer name. SEB checks manufacturer string against known VM vendors. If manufacturer appears as 'Dell'/'HP' etc., this check passes. BUT SEB also checks PCI devices, MAC address, system hardware -- those may still catch it.",
      "", "High", "Medium", "To Test",
      "This tests SEB's VM detection depth. Even if this alone doesn't bypass, it shows which checks are actually effective."],

    ["REG-146", "SEB Bypass - Vector 6", "VMware SMBIOS + MAC Spoof (No DLL Patch)", "Negative",
      "Combine SMBIOS reflection with MAC address spoofing using official SEB",
      "VMware Workstation, official SEB",
      "1. SMBIOS.reflectHost = \"TRUE\" in .vmx\n2. ethernet0.address = \"00:50:56:XX:XX:XX\" (non-VMware prefix) in .vmx\n3. Boot VM, install official SEB\n4. Launch SEB\n5. Does it bypass both manufacturer AND MAC checks?\n6. PCI device check may still catch VMware devices",
      "Manufacturer + MAC both spoofed. SEB's remaining check is PCI vendor IDs. If VMware PCI devices are visible, detection may still trigger.",
      "", "High", "Medium", "To Test",
      "Each layer of spoofing neutralizes one detection method. Testing layer by layer reveals exactly which checks work."],

    // Vector 7: Combination Attack (Maximum Stealth)
    ["REG-147", "SEB Bypass - Vector 7", "Full Stealth: VM + SMBIOS + AI DLLs + Log Tamper", "Negative",
      "Maximum stealth attack combining all bypass techniques",
      "VMware + SMBIOS + AI-generated bypass DLLs + log editing tools",
      "1. VMware with SMBIOS.reflectHost = TRUE\n2. MAC address spoofed\n3. Install SEB from source with AI-modified DLLs (REG-141)\n4. Launch SEB in VM\n5. Take exam\n6. After exam: edit Runtime.log to remove any VM indicators\n7. Edit Client.log to remove VMware service entries\n8. Verify: Config Key passes, BEK not checked, logs clean, User-Agent shows correct version\n9. Can invigilator detect ANYTHING?",
      "Complete invisibility. Zero detection by current system. Config Key passes. No BEK check. Logs tampered. User-Agent spoofed. ONLY defense: BEK validation + SEB Verificator.",
      "", "Critical", "High", "To Test",
      "This is Scenario F + AI DLLs + log tampering combined. The ultimate test."],

    // Admin Config URL Exposure (NEW VECTOR)
    ["REG-148", "SEB Admin - Security", "Admin Config URL Accessible to Students", "Negative",
      "Student discovers /admin/seb-config URL and tries to access it",
      "Student has valid auth token from exam session",
      "1. Student inspects network requests in browser (before SEB launches)\n2. Finds /admin/seb-config endpoint\n3. Tries accessing directly with auth token\n4. Gets 400 error -- but WHAT information does the 400 response contain?\n5. Does the response leak config details, error messages, or API structure?\n6. Try with different HTTP methods (GET, POST, PUT, DELETE)\n7. Try with modified headers\n8. Try IDOR: /admin/seb-config/1, /admin/seb-config/2 etc.",
      "Should return 403 Forbidden (not 400 Bad Request). 400 means server processed the request partially. Should use proper role-based access control.",
      "", "High", "Low", "To Test",
      "400 vs 403 is important. 400 means the endpoint exists and is processing -- just rejecting bad input. 403 would mean proper access denied."],

    ["REG-149", "SEB Admin - Security", "Auth Token Hijacking for Config Access", "Negative",
      "Student intercepts admin auth token to access SEB config",
      "Student on same network, proxy tools (Burp Suite / MITM)",
      "1. If HTTP (not HTTPS): student can MITM to capture admin token\n2. If HTTPS: student uses Burp Suite proxy on their own machine to inspect headers\n3. Student captures X-SafeExamBrowser-ConfigKeyHash header value\n4. Can this hash be reverse-engineered to get Config Key?\n5. Can student use captured headers to impersonate admin?\n6. Try: replay admin API calls with student's auth token\n7. Try: escalate student role to admin via API parameter tampering",
      "Admin endpoints should be completely inaccessible with student tokens. Config Key hash is SHA256 -- not reversible. But if RBAC is weak, privilege escalation may be possible.",
      "", "Critical", "Medium", "To Test",
      "Test: send student token to admin endpoints. Does server return 401/403 or does it return data?"],

    ["REG-150", "SEB Admin - Security", "SEB Config File Download by Student", "Negative",
      "Student tries to download the .seb config file from admin endpoint",
      "Student auth token, knowledge of admin URL",
      "1. Try: GET /admin/seb-config/download with student token\n2. Try: GET /api/seb/config with student token\n3. Try: enumerate common API paths for config download\n4. If .seb file is downloadable: student can extract Config Key\n5. With Config Key: student can generate their own .seb file with relaxed settings\n6. Test: is config key visible in any student-facing API response?",
      "Student should NEVER be able to download .seb file or see Config Key. If they can: they can create their own config with VM detection disabled.",
      "", "Critical", "Medium", "To Test",
      ".seb file contains ALL security settings. If compromised, student knows exactly what to bypass."],

    // Server-Side Detection Gap Analysis
    ["REG-151", "Server Detection Gap", "Does Server Check SEB Version in User-Agent?", "Edge Case",
      "Determine if our server parses User-Agent for SEB version enforcement",
      "SEB with different versions, network inspection tool",
      "1. Use SEB v3.6.0 -- capture User-Agent (should show SEB/3.6.0)\n2. Install SEB v3.5.0 -- does User-Agent show SEB/3.5.0?\n3. Try exam with each version\n4. Does server accept both?\n5. Check server logs: is User-Agent logged?\n6. If no version check: ANY old SEB version works\n7. Test with curl: manually set User-Agent to SEB/3.6.0 without actual SEB -- does server accept?",
      "If server doesn't check version: student can use any old bypassed version. If server only checks User-Agent string: student can spoof it in custom build.",
      "", "Critical", "Low", "To Test",
      "FUNDAMENTAL gap analysis. Determines attack surface for Vectors 2 and 5."],

    ["REG-152", "Server Detection Gap", "Does Server Validate BEK (X-SafeExamBrowser-RequestHash)?", "Edge Case",
      "Determine if our server validates Browser Exam Key at all",
      "Official SEB, patched SEB, network inspector",
      "1. Use official SEB -- inspect HTTP headers sent\n2. Is X-SafeExamBrowser-RequestHash header present?\n3. If present: is server validating it?\n4. Use patched SEB -- is the hash different?\n5. If server doesn't validate BEK: ALL DLL-patching attacks work\n6. If server validates BEK: DLL patching is detected (this would be good)",
      "If BEK is sent AND validated: DLL patching is detectable. If BEK is not sent or not validated: no defense against binary tampering.",
      "", "Critical", "Low", "To Test",
      "This is THE critical question. If BEK is validated, Vectors 1-4 are all detectable. If not, we have zero defense."],

    ["REG-153", "Server Detection Gap", "Does Server Log SEB-Related Headers?", "Edge Case",
      "Determine what SEB headers the server captures and logs",
      "Server access or API inspection",
      "1. Take exam via SEB normally\n2. Check server logs: what SEB headers are recorded?\n3. Is User-Agent stored? Is ConfigKeyHash stored? Is RequestHash stored?\n4. Are these available in the admin console?\n5. Can invigilator see which SEB version a student used?\n6. If nothing is logged: even detectable attacks leave no evidence",
      "Server should log: User-Agent (with SEB version), ConfigKeyHash, RequestHash (BEK), client IP, timestamp. Without logging, even detection is useless.",
      "", "High", "Low", "To Test",
      "Logging is the foundation of forensic analysis. If headers aren't logged, security is blind."],

    // Additional edge cases
    ["REG-154", "SEB Bypass - Custom Fork", "Student Forks SEB and Removes All Security", "Negative",
      "Student creates entirely custom SEB build from open source with all security removed",
      "GitHub account, Visual Studio, .NET Framework SDK",
      "1. Fork https://github.com/SafeExamBrowser/seb-win-refactoring\n2. Remove ALL security: VM detection, process monitoring, display monitoring, clipboard restriction, keyboard hooks\n3. Keep: browser functionality, Config Key generation (so server accepts)\n4. Build entire solution\n5. Install custom SEB\n6. All lockdown features disabled\n7. Alt+Tab works, clipboard works, Task Manager works\n8. Config Key STILL PASSES because .seb config is unchanged",
      "Student has unrestricted browser. Only Config Key validates. No lockdown features active. This is the ultimate bypass -- an 'SEB-shaped Chrome'.",
      "", "Critical", "High", "To Test",
      "Hardest to defend against without BEK. The custom build produces valid Config Key but different BEK hash."],

    ["REG-155", "SEB Bypass - User-Agent Spoof", "curl/Postman with Spoofed SEB Headers", "Negative",
      "Student uses API tools to submit exam without any browser at all",
      "curl, Postman, or custom script",
      "1. Capture all HTTP headers SEB sends during exam\n2. Replicate headers in curl/Postman: User-Agent, ConfigKeyHash, RequestHash\n3. Send API requests directly to exam endpoints\n4. If Config Key is predictable (SHA256 of URL + known key): student can compute it\n5. Submit answers via API without any browser\n6. No camera, no lockdown, no restrictions at all",
      "If successful: student takes exam via raw HTTP with zero restrictions. Defense: server must validate that responses come from a real SEB browser session, not just check headers.",
      "", "Critical", "High", "To Test",
      "Tests if security is header-based only. If server relies solely on HTTP headers without session binding, this attack is trivial."],
  ];

  newRegCases.forEach(d => {
    const row = addRow(ws5, d);
    applySev(row, 10);
    applyStatus(row, 12);
  });

  ws5.autoFilter = { from: { row: 1, column: 1 }, to: { row: ws5.rowCount, column: 13 } };

  // =========================================================================
  // SHEET 4: STEALTH CHEAT -- Add AI-generated bypass as stealth method
  // =========================================================================
  const ws4 = wb.getWorksheet("4. Cheat - Stealth");

  const newStealth = [
    ["CS-042", "SEB Bypass - AI", "AI-generated bypass DLLs from open source SEB code",
      "Student uses ChatGPT/Claude to analyze public SEB source on GitHub, generates modified C# files that neutralize all VM detection, process monitoring, and integrity checks. Compiles version-matched DLLs. No download trail from bypass sites.",
      "NO", "Config Key only validates .seb config, NOT binaries. BEK not implemented. No server-side binary hash check.",
      "None", "Medium", "100% Stealth",
      "CRITICAL: Implement BEK validation. This is the only defense. Also consider: code signing validation, SEB Verificator integration.",
      "To Test"],
    ["CS-043", "SEB Admin Exploit", "Student accesses admin SEB config URL and steals Config Key",
      "Student discovers /admin/seb-config URL (visible in network tab before SEB launches), attempts to access with stolen/escalated auth token. If Config Key is exposed, student can generate their own permissive .seb config.",
      "MAYBE", "Depends on RBAC implementation. If 400 error leaks info vs proper 403.",
      "Medium", "Medium", "High",
      "Ensure: proper 403 for unauthorized access, no Config Key in student-facing responses, rate limiting on admin endpoints.",
      "To Test"],
    ["CS-044", "SEB Bypass - Headers", "Spoofed SEB headers via curl/Postman to take exam without SEB",
      "Student captures all SEB HTTP headers (User-Agent, ConfigKeyHash) from a single legitimate session, then replays them via curl/Postman to submit exam answers via API. No browser restrictions apply.",
      "MAYBE", "If server validates session binding beyond just headers: detectable. If header-only: undetectable.",
      "None if undetected", "High", "100% Stealth if works",
      "Implement: session binding, request signing, behavioral analysis (timing between API calls), CAPTCHA-like challenges.",
      "To Test"],
  ];

  newStealth.forEach(d => {
    const row = addRow(ws4, d);
    applyStatus(row, 11);
  });

  // =========================================================================
  // SHEET 2: FOUND BUGS -- Add admin URL exposure bug
  // =========================================================================
  const ws2 = wb.getWorksheet("2. Found Bugs");

  const newBugs = [
    ["BUG-019", "SEB Admin Security", "Admin SEB config URL returns 400 instead of 403 for unauthorized access",
      "1. Log in as student\n2. Navigate to /admin/seb-config\n3. Observe 400 Bad Request response",
      "Should return 403 Forbidden -- endpoint should not be accessible",
      "Returns 400 Bad Request -- indicates server processes the request partially before rejecting. May leak endpoint structure.",
      "High", "P1", "Chrome / Student account", "Screenshot provided by tester",
      "To Verify", "400 means the route exists and code executed. 403 would mean proper RBAC rejection. Need to check response body for information leakage."],
    ["BUG-020", "SEB Security Architecture", "No Browser Exam Key (BEK) validation implemented -- ALL DLL patching attacks succeed",
      "1. Use patched SEB DLLs\n2. Take exam\n3. Observe: Config Key validation passes\n4. No X-SafeExamBrowser-RequestHash validation on server",
      "Server should validate BEK to detect binary tampering",
      "Server only validates Config Key (X-SafeExamBrowser-ConfigKeyHash). BEK (X-SafeExamBrowser-RequestHash) is not checked. Any patched/modified SEB binary is accepted.",
      "Critical", "P0", "All environments", "Confirmed via code analysis and testing",
      "Confirmed", "This is the #1 security vulnerability. Without BEK, DLL patching, custom forks, and AI-generated bypasses ALL work undetected."],
    ["BUG-021", "SEB Security Architecture", "No SEB version enforcement -- old/bypassed versions accepted",
      "1. Install SEB v3.5.0 (or v2.4)\n2. Take exam\n3. Check if server accepts older version",
      "Server should enforce minimum SEB version",
      "To be verified: does User-Agent contain SEB version? Does server parse it? Does it reject old versions?",
      "Critical", "P0", "All environments", "Pending test",
      "To Verify", "If server accepts SEB v2.4 (no VM detection), the entire SEB security is meaningless."],
  ];

  newBugs.forEach(d => {
    const row = addRow(ws2, d);
    applySev(row, 7);
    applyStatus(row, 11);
  });

  // =========================================================================
  // SHEET 6: EDGE CASES -- Add new security edge cases
  // =========================================================================
  const ws6 = wb.getWorksheet("6. Edge Cases & Open Ends");

  const newEdge = [
    ["EC-024", "Security", "Admin config URL leaks API structure via 400 error response body",
      "Edge Case",
      "When student accesses /admin/seb-config and gets 400, the response body may contain: error details, expected parameters, API version, stack trace, or internal endpoint names. Each piece of info helps an attacker understand the system.",
      "Information disclosure leading to targeted attacks",
      "High", "To Test", "Check response body carefully for any leaked information"],
    ["EC-025", "Security", "Can student compute Config Key from observed traffic?",
      "Edge Case",
      "Config Key = SHA256(URL + ConfigKey). If student observes multiple ConfigKeyHash values for different URLs, can they reverse-engineer the Config Key? SHA256 is not reversible, but if the key space is small or predictable, brute-force may work.",
      "If Config Key is compromised, student can generate permissive .seb configs",
      "High", "To Test", "Config Key is 64-char hex -- brute force infeasible. But if admin uses weak/default key: vulnerable."],
    ["EC-026", "Security", "SEB session AES encryption key/IV hardcoded in source code",
      "Note",
      "IntegrityModule.cs contains hardcoded SESSION_DATA_KEY and SESSION_DATA_IV for encrypting session cache. Since SEB is open source, these values are public knowledge. A student can decrypt and manipulate the session cache file.",
      "Session integrity can be compromised",
      "Medium", "Note", "The keys are: IV=120714020310141811010415061605 12, Key=010407080910130611141516050313060104020314150708111216050910 1202"],
    ["EC-027", "Security", "AI can generate complete SEB bypass in under 15 minutes",
      "Note",
      "Tested: Given the public SEB source code on GitHub, AI (ChatGPT/Claude) can analyze VirtualMachineDetector.cs, RemoteSessionDetector.cs, and IntegrityModule.cs and generate bypass modifications in a single prompt. Total time from source code to compiled bypass DLL: ~15 minutes for someone with basic C# knowledge.",
      "Extremely low barrier for creating custom, version-matched, untraceable bypasses",
      "Critical", "Confirmed", "PoC created in SEB_Bypass_PoC/ folder. This fundamentally changes the threat model -- security through obscurity is impossible."],
    ["NOTE-010", "Note", "Complete SEB Bypass Threat Model -- 7 Attack Vectors Identified",
      "Note",
      "Vector 1: Pre-built patch (SEBPatch, 194+ weekly downloads)\nVector 2: Downgrade + old patch (SEB v3.5.0 + nxvvvv)\nVector 3: Custom SEB fork from source\nVector 4: AI-generated bypass DLLs (PoC created)\nVector 5: Legacy SEB v2.4 (zero VM detection)\nVector 6: VM anti-detection without DLL patching (SMBIOS + MAC spoof)\nVector 7: Combination attack (VM + DLLs + log tamper)\nALL vectors bypass Config Key. ONLY BEK validation detects Vectors 1-4.",
      "Without BEK implementation, 4 out of 7 vectors are completely undetectable",
      "Critical", "Confirmed", "Added REG-138 through REG-155 for systematic testing of all vectors"],
  ];

  newEdge.forEach(d => {
    const row = addRow(ws6, d);
    applySev(row, 7);
    applyStatus(row, 8);
  });

  // =========================================================================
  // SHEET 7: SUMMARY DASHBOARD -- Update counts
  // =========================================================================
  const ws7 = wb.getWorksheet("SUMMARY DASHBOARD");
  const bugCount = ws2.rowCount - 1;
  const detCount = wb.getWorksheet("3. Cheat - Detectable").rowCount - 1;
  const stealthCount = ws4.rowCount - 1;
  const regCount = ws5.rowCount - 1;
  const edgeCount = ws6.rowCount - 1;
  const grandTotal = bugCount + detCount + stealthCount + regCount + edgeCount;

  for (let r = 1; r <= ws7.rowCount; r++) {
    const cell = ws7.getRow(r).getCell(1);
    const val = String(cell.value || "");
    if (val.includes("Total Found Bugs")) ws7.getRow(r).getCell(2).value = bugCount;
    if (val.includes("Total Detectable")) ws7.getRow(r).getCell(2).value = detCount;
    if (val.includes("Total Stealth")) ws7.getRow(r).getCell(2).value = stealthCount;
    if (val.includes("Total Regression")) ws7.getRow(r).getCell(2).value = regCount;
    if (val.includes("Total Edge Cases")) ws7.getRow(r).getCell(2).value = edgeCount;
    if (val.includes("GRAND TOTAL")) ws7.getRow(r).getCell(2).value = grandTotal;
  }

  // Add new summary rows for the 7-vector threat model
  addRow(ws7, []);
  const headerRow = addRow(ws7, ["SEB BYPASS THREAT MODEL -- 7 VECTORS", "", ""]);
  headerRow.font = { bold: true, size: 12, name: "Calibri", color: { argb: "FFFFFFFF" } };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFF0000" } };

  const vectorSummary = [
    ["Vector 1: Pre-Built Patch (SEBPatch)", "Active threat. 194+ weekly downloads. Covers latest SEB v3.10.1. Zero skill needed.", "CRITICAL - To Test"],
    ["Vector 2: Downgrade + Old Patch", "Student installs old SEB + matching patch. Depends on server version check.", "CRITICAL - To Test"],
    ["Vector 3: Custom SEB Fork", "Student forks open-source SEB, removes all security, compiles. Config Key still passes.", "CRITICAL - To Test"],
    ["Vector 4: AI-Generated Bypass DLLs", "Student uses ChatGPT to modify 3 C# files. Version-matched. No download trail. PoC CREATED.", "CRITICAL - PoC Ready"],
    ["Vector 5: Legacy SEB v2.4", "Zero VM detection. If server accepts old versions, complete bypass.", "CRITICAL - To Test"],
    ["Vector 6: VM Anti-Detection (No DLL)", "SMBIOS + MAC spoof with official SEB. Even BEK wouldn't detect this.", "HIGH - To Test"],
    ["Vector 7: Combination (Full Stealth)", "VM + AI DLLs + SMBIOS + Log Tamper. Zero detection possible.", "CRITICAL - To Test"],
    ["", "", ""],
    ["Admin Exploit: Config URL Exposure", "Student accesses /admin/seb-config, gets 400 instead of 403. Possible info leak.", "HIGH - To Test"],
    ["Admin Exploit: Auth Token Hijack", "Student uses captured token for admin API access. RBAC enforcement unknown.", "CRITICAL - To Test"],
    ["Server Gap: No BEK Validation", "THE #1 vulnerability. Without BEK, Vectors 1-4 are ALL undetectable.", "CRITICAL - CONFIRMED"],
    ["Server Gap: No Version Enforcement", "Server may accept any SEB version including v2.4 with zero security.", "CRITICAL - To Test"],
    ["Server Gap: No SEB Header Logging", "If SEB headers aren't logged, even detectable attacks leave no evidence.", "HIGH - To Test"],
  ];

  vectorSummary.forEach(d => {
    const row = addRow(ws7, d);
    const status = String(d[2] || "").toLowerCase();
    if (status.includes("critical")) {
      row.getCell(3).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.criticalRed } };
      row.getCell(3).font = { bold: true, size: 10, name: "Calibri", color: { argb: COLORS.headerFont } };
    } else if (status.includes("high")) {
      row.getCell(3).fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.highOrange } };
      row.getCell(3).font = { bold: true, size: 10, name: "Calibri", color: { argb: COLORS.headerFont } };
    }
  });

  await wb.xlsx.writeFile("EMS_Exam_Security_TestPlan.xlsx");

  console.log("\n=== COMPREHENSIVE EXCEL UPDATE COMPLETE ===");
  console.log(`  Bugs: ${bugCount} (added BUG-019, BUG-020, BUG-021)`);
  console.log(`  Stealth: ${stealthCount} (added CS-042, CS-043, CS-044)`);
  console.log(`  Regression: ${regCount} (added REG-138 to REG-155)`);
  console.log(`  Edge Cases: ${edgeCount} (added EC-024 to EC-027, NOTE-010)`);
  console.log(`  Grand Total: ${grandTotal}`);
  console.log(`  Summary Dashboard: Updated with 7-Vector Threat Model`);
}

main().catch(e => console.error(e));
